# Generated by Django 5.2.4 on 2025-08-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_title', models.CharField(blank=True, max_length=124, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('station_Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='emergencycall.stationcatagory')),
            ],
        ),
    ]
