# Generated by Django 5.2.4 on 2025-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='station_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
