# Generated by Django 5.2.4 on 2025-08-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycall', '0002_stationinfo_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationinfo',
            name='station_location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
