# Generated by Django 5.2.4 on 2025-08-10 15:24

import emergencycall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencycall', '0003_stationinfo_station_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationcatagory',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='profile/', validators=[emergencycall.models.image_validator]),
        ),
    ]
