# Generated by Django 5.2.4 on 2025-08-09 17:29

import django.db.models.deletion
import safetyguide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='profile/', validators=[safetyguide.models.image_validator])),
                ('title', models.CharField(blank=True, max_length=124, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='safetyguide.safetyguide')),
            ],
        ),
    ]
