# Generated by Django 5.2.4 on 2025-08-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_location_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=124, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(blank=True, max_length=128, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('organaization_name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='certification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.certification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.experience'),
        ),
    ]
